project:
  type: book

execute:
  eval: true
  echo: true  # so we can have code folding
  output: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed
  freeze: false  # during global project renders, re-render only when source changes
  
book:
  title: "Filers and nonfilers"
  subtitle: ""
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - prepare.qmd
    # - part: "Revenue options"
    #   chapters:
    #   - options/summary.qmd
    #   - options/legislation_links.qmd
    #   - options/budget_bills.qmd
    # - part: "Appendix"
    #   chapters: 
    #   - appendix.qmd
    
# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true    
  # pdf:
  #   documentclass: scrreprt

# editor: console

editor_options:
  chunk_output_type: console

  
  
# renv-related commands
# renv::snapshot()
# renv::restore()
# renv::update()
# renv::status()
# Sys.getenv("RENV_PATHS_CELLAR") # RENV_PATHS_SOURCE RENV_PATHS_RENV
  
  
# useful reminders of quarto commands:
# quarto publish netlify --no-render
# quarto publish netlify --no-browser --no-prompt
# quarto publish netlify --no-render --no-browser --no-prompt  

# boyd-mta202324.netlify.app
  
  
# possibly use this at start of each doc??
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  