---
output: html_document
editor_options: 
 chunk_output_type: console
---


# Get files

## Load packages

```{r}
#| label: includes

source(here::here("r", "libraries.r"))

# E:\R_projects\projects\taxdata-psl\data\IRS spreadsheets

```

## Define folder names and other constants


```{r}
#| label: constants

tddir <- r"(E:\data\taxdata-psl)"

# URL of tax-calculator variables json file
url <- "https://raw.githubusercontent.com/PSLmodels/Tax-Calculator/master/taxcalc/records_variables.json"

url_pe_flat <- "https://github.com/PSLmodels/tax-microdata-benchmarking/releases/download/policyengine-cps-flat-file/tax_microdata.csv.gz"

wrp <- r"(c:\Program Files\WinRAR\WinRAR.exe)"
pez <- path(tddir, "tax_microdata.csv.gz")

```




```{r}
#| label: download-pe-flatfile
#| eval: false

# only update when the pe flatfile changes
download.file(url=url_pe_flat, destfile = pez, mode="wb")

```


```{r}
#| label: get-tdata-and-vars

tcvars <- readRDS(here::here("data", "tcvars.rds"))
# ht(tcvars)

utcvars <- tcvars |> 
  select(vname, vtype, desc) |> 
  distinct()


# get frozen tax-calculator file for 2023 ----
tdfn <- "tc23.csv"
tdpath <- path(tddir, tdfn)
tddf <- vroom(tdpath) # Rows: 252868 Columns: 209
# glimpse(tddf)

```



```{r}
#| label: get-pedata-and-date

# get the file modification date of the csv file using winrar (wrp)
#   because that will not change the date the way other utilities do

# un-winrar the file
command <- sprintf('"%s" x -ibck -o+ "%s" "*.*" "%s"', wrp, pez, tddir)
system(command, wait = TRUE)

# now that we have the file unzipped, get its date
pefn <- "tax_microdata.csv"
pepath <- path(tddir, pefn)
pedata <- file_info(pepath)
# glimpse(pedata)
pedate <- pedata$modification_time
# we can delete the csv file if we want

## get the pe data directly from the gz file ----
pedf <- vroom(pez) # read directly from the gz file Rows: 155312 Columns: 62                                                                                                                                                                                        
# glimpse(pedf)

```


```{r}

glimpse(pedf)
skim(pedf)
ns(pedf)

pedf |> 
  summarise(n=n(), 
            wtdn=sum(s006),
            wages=sum(e00200 * s006),
            .by=is_tax_filer) |> 
  gt() |>
   
  fmt_number(columns=c(n, wtdn),
             scale=1,
             decimals=0) |> 
  fmt_number(columns=c(wages),
             scale=1e-9,
             decimals=3)



```


